#!/usr/bin/env python3

import rospy
from arm_kinematics.fk_broadcaster import Foward_Kinematics_Broadcaster

if __name__ == '__main__':
    rospy.init_node('fk_broadcaster_node')
    rospy.loginfo("Creating fk_broadcaster")
    broadcaster = Foward_Kinematics_Broadcaster()
    rospy.spin()