#!/usr/bin/env python

import rospy
from car_final_project.planner_ros import PlannerROSWithControl
from geometry_msgs.msg import PoseStamped
from std_msgs.msg import Header


if __name__ == "__main__":
    rospy.init_node("planner")

    PlannerROSWithControl(
        num_vertices=rospy.get_param("~num_vertices"),
        connection_radius=float(rospy.get_param("~connection_radius")),
        curvature=float(rospy.get_param("~curvature")),
        tf_prefix=rospy.get_param("~tf_prefix", ""),
    )
    rospy.spin()
