#!/usr/bin/env python
import signal

import rospy
from car_controller.control_ros import (
    ControlROS,
    get_ros_params,
    controllers,
)


def interrupt_signal(x, y):
    node.shutdown()
    exit(0)


if __name__ == "__main__":
    rospy.init_node("controller", disable_signals=True)
    controller_type, params = get_ros_params()
    rospy.loginfo("Using {} controller".format(controller_type))

    controller = controllers[controller_type](**params)

    node = ControlROS(controller)
    signal.signal(signal.SIGINT, interrupt_signal)
    node.start()
    rospy.spin()
