#!/usr/bin/env python

import rospy  # ROS Python API
from std_msgs.msg import Int64, String, Bool  # ROS message type


from introduction.prime_number import is_prime_number

# This if-statement is a common Python idiom. If we run this script directly
# (e.g. with python3 ./prime_number), this will be the code entrypoint. If this
# file were imported by another script, however, the condition would evaluate to
# False and code inside won't run.
if __name__ == "__main__":

    # Every node registers itself with the ROS master process, so we must pass a
    # name for the node. (A good practice is to use the same name as the script,
    # but it's up to you.)
    rospy.init_node("prime_number")

    # Here's an example to get parameters from ROS. Note that the name starts
    # with ~. Just name your parameters following this convention for now.
    #
    # Function signature: rospy.get_param(parameter_name, default_value)
    prime_topic = rospy.get_param("~output_topic", "/introduction/prime_number_output")

    # Get the value of the "~test_number" parameter from ROS. Don't forget
    # to make sure it's the right type (an integer)! Feel free to specify a
    # default value.
    # BEGIN QUESTION 1.2
    "*** REPLACE THIS LINE ***"
    test_number = rospy.get_param("~test_number", 7)
    test_number = int(test_number)
    # END QUESTION 1.2

    # Here's an example to create a ROS publisher. The queue_size defines how
    # many messages to buffer when waiting to send messages. In general, a large
    # number will be useful when many messages will be sent. We are sending
    # messages infrequently, 1 is okay.
    #
    # Function signature: rospy.Publisher(topic_name, msg_type, queue_size)
    example_publisher = rospy.Publisher("/introduction/example", String, queue_size=1)

    # Using the above example as reference, create a publisher to the topic whose topic name is stored in the variable “prime_topic”.
    # The example publisher publishes String messages;
    # what type of messages do we want to publish from our prime_number publisher?
    # (Hint: check the imports at the top of the file.)
    # BEGIN QUESTION 1.2
    "*** REPLACE THIS LINE ***"
    prime_publisher = rospy.Publisher(prime_topic, Bool, queue_size=1)
    # END QUESTION 1.2

    # It can take some time for the publisher to be ready, so we'll wait before
    # we start to publish. (The specific wait time isn't important, but for
    # completeness, this waits for 0.5 seconds.)
    rospy.sleep(0.5)

    example_publisher.publish("Hello World!")

    # Call is_prime_number with the test number you obtained earlier, then publish
    # a boolean result.
    # BEGIN QUESTION 1.2
    "*** REPLACE THIS LINE ***"
    prime_result = is_prime_number(test_number)
    prime_publisher.publish(Bool(prime_result))
    # END QUESTION 1.2
